GET http://localhost:8012//config/rabbitmq
Accept: application/json

###
GET http://localhost:8011/config/redis
Accept: application/json

###
GET http://localhost:8011/user/getUser
Accept: application/json

###
GET http://localhost:8012/order/makeOrder
Accept: application/json

###
GET http://localhost:8012/order/makeOrder2
Accept: application/json
